In [ ]:
import numpy as np

In [ ]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [ ]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [ ]:
def evaluate_population( pop ):
    """
    Hàm đánh giá tất cả cá thể trong quần thể.
    
    Arguments:
    pop -- Quàn thể cần được đánh giá.

    Returns:
    values -- Giá trị của tất cả các cá thể trong quần thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    values = np.array([onemax(ind) for ind in pop])
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return values

In [ ]:
def better_fitness( fitness_1, fitness_2, maximization=True ):
    """
    Hàm so sánh độ thích nghi của 2 cá thể.
    
    Arguments:
    fitness_1 -- Độ thích nghi của cá thể 1.
    fitness_2 -- Độ thích nghi của cá thể 2.
    maximization -- Biến boolean cho biết bài toán đang giải thuộc dạng tối đa hoá (mặc định) hay không
    
    Returns:
    True nếu fitness_1 tốt hơn fitness_2. Ngược lại, trả về False.
    """
    
    if maximization:
        if fitness_1 > fitness_2:
            return True
    else:
        if fitness_1 < fitness_2:
            return True
        
    return False

In [ ]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size):
    """
    Hàm chọn lọc cạnh tranh.
    
    Arguments:
    pop -- Quần thể để thực hiện phép chọn lọc.
    pop_fitness -- Mảng 1 chiều chứa giá trị (độ thích nghi) của từng cá thể trong quần thể.
    selection_size -- Số lượng cá thể sẽ được chọn.
    tournament_size -- Kích thước của tournament: Số lượng các cá thể được so sánh với nhau mỗi lần.
    
    Returns:
    selected_indices -- Chỉ số của những cá thể trong quần thể pop được chọn. Chỉ số có thể được lặp lại.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    indices = np.arange(num_individuals)
    selected_indices = []
    
    while len(selected_indices) < selection_size:
        # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể.
        np.random.shuffle(indices)
        
        for i in range(0, num_individuals, tournament_size):
          best_idx = i
          for idx in range(1, tournament_size):
            if better_fitness(pop_fitness[indices[i+idx]], pop_fitness[indices[best_idx]]):
              best_idx = i + idx
          selected_indices.append(indices[best_idx])
    
    selected_indices = np.array(selected_indices)        

    ### DỪNG CODE TẠI ĐÂY ###
    
    return selected_indices

In [ ]:
def variation( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        for idx in range(0, num_parameters):
          r = np.random.rand()
          if r < 0.5:
            temp = offspring2[idx]
            offspring2[idx] = offspring1[idx]
            offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [ ]:
def popop(num_individuals, num_parameters, num_generations):
    """
    Hàm cài đặt thuật giải di truyền theo các bước P->O->(P+O)->P
    
    Arguments:
    num_individuals -- Số lượng cá thể trong quần thể.
    num_parameters -- Số lượng biến.
    num_generations -- Số thế hệ thuật toán sẽ chạy.

    Returns:
    In ra quần thể ở thế hệ cuối cùng và giá trị của từng cá thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    # Khởi tạo quần thể
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = evaluate_population(pop)
    # print("#Gen 0:")
    # print(pop)
    # print(pop_fitness)
    
    # Sử dụng tournament_size 4 và selection_size là bằng kích thước quần thể
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):
        # Tạo ra các cá thể con và đánh giá chúng
        offspring = variation(pop)
        offspring_fitness = evaluate_population(offspring)
        
        # Tạo ra quần thể pool gồm quần thể hiện tại pop và offspring
        pool = np.vstack((pop,offspring))
        pool_fitness = np.hstack((pop_fitness, offspring_fitness))

        # Thực hiện tournament selection trên quần thể pool 
        pool_indices = tournament_selection(pool, pool_fitness, selection_size, tournament_size)

        # Thay thế quần thể hiện tại bằng những cá thể được chọn ra từ pool.
        pop = pool[pool_indices, :]
        pop_fitness = pool_fitness[pool_indices]
        # print("#Gen {}:".format(i+1))
        # print(pop_fitness)

    ### DỪNG CODE TẠI ĐÂY ###
    # print("#Result:")
    # print(pop)
    # print(pop_fitness)

    return pop_fitness

In [ ]:
def evaluate_algorithm(num_individuals, num_parameters, num_generations):
  count = 0
  for i in range(30):
    np.random.seed(i)
    final_offspring = popop(num_individuals, num_parameters, num_generations)
    if num_parameters in final_offspring:
      count +=1

  return count

In [ ]:
# Trường hợp kích thước quần thể là 4
np.random.seed(1)
num_parameters = 20
num_individuals = 4
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[11  8 13 11]
#Gen 1:
[13 13 13 13]
#Gen 2:
[15 13 15 14]
#Gen 3:
[15 16 16 15]
#Gen 4:
[16 16 16 16]
#Gen 5:
[16 16 16 16]
#Gen 6:
[16 16 16 16]
#Gen 7:
[16 16 16 16]
#Gen 8:
[16 16 16 16]
#Gen 9:
[16 16 16 16]
#Gen 10:
[16 16 16 16]
#Result:
[[1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0]]
[16 16 16 16]


In [ ]:
# Trường hợp kích thước quần thể là 8
np.random.seed(1)
num_parameters = 20
num_individuals = 8
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[11  8 13 11 12 10 12  9]
#Gen 1:
[12 13 13 13 13 12 13 12]
#Gen 2:
[13 15 14 13 14 13 13 15]
#Gen 3:
[15 15 15 17 17 14 15 15]
#Gen 4:
[17 17 17 17 17 17 15 17]
#Gen 5:
[17 17 18 18 18 17 17 17]
#Gen 6:
[18 18 18 18 17 18 18 18]
#Gen 7:
[18 18 18 18 18 18 18 18]
#Gen 8:
[19 18 19 18 19 19 18 19]
#Gen 9:
[19 19 19 19 19 19 19 19]
#Gen 10:
[19 19 19 19 19 19 19 19]
#Result:
[[1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]]
[19 19 19 19 19 19 19 19]


In [ ]:
# Trường hợp kích thước quần thể là 16
np.random.seed(1)
num_parameters = 20
num_individuals = 16
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[11  8 13 11 12 10 12  9  8  7 10 13 12 10  8 11]
#Gen 1:
[10 12 14 13 12 11 13 15 10 15 12 13 12 12 14 13]
#Gen 2:
[15 14 15 14 13 13 15 13 15 14 15 15 14 13 15 14]
#Gen 3:
[15 15 18 15 15 16 15 14 18 15 15 16 15 15 15 15]
#Gen 4:
[16 18 18 19 16 15 15 19 16 18 15 16 19 16 15 19]
#Gen 5:
[19 17 19 19 18 18 19 19 19 18 19 19 19 19 19 19]
#Gen 6:
[19 20 19 19 19 19 19 19 19 19 19 19 19 19 19 20]
#Gen 7:
[20 20 20 19 20 19 20 19 19 19 20 20 19 20 20 20]
#Gen 8:
[20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]
#Gen 9:
[20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]
#Gen 10:
[20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]
#Result:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 

In [ ]:
# Hãy thay đổi random seed, số lượng biến, kích thước quần thể, số thế hệ 
# và quan sát thuật toán có giải được bài toán hay không.
np.random.seed(13)
num_parameters = 20
num_individuals = 10
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[ 4 10 13  9 13 14 11  7 12 11]
#Gen 1:
[10 13 14 13 10 13 13 12 14 13]
#Gen 2:
[14 13 13 14 14 14 14 13 14 13]
#Gen 3:
[14 14 14 14 15 14 15 14 15 14]
#Gen 4:
[16 14 15 16 15 15 16 15 16 15]
#Gen 5:
[17 15 17 16 16 16 17 16 16 17]
#Gen 6:
[17 18 17 16 17 17 17 18 17 17]
#Gen 7:
[17 18 18 18 18 18 18 18 17 18]
#Gen 8:
[18 18 18 18 18 18 18 18 18 18]
#Gen 9:
[18 18 18 18 18 18 18 18 18 18]
#Gen 10:
[18 18 18 18 18 18 18 18 18 18]
#Result:
[[1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]]
[18 18 18 18 18 18 18 18 18 18]


In [ ]:
num_parameters = 4
num_individuals = 8
num_generations = 10
evaluate_algorithm(num_individuals, num_parameters, num_generations)

28